Repository freshjuice-dev/freshjuice.dev, pull requests merged in 2024-08, with the labels that each got.

#10 Update sorting for docs page
  cfg/_11ty/filters.js
  src/_includes/layouts/docs.njk
  src/content/docs/index.md
Labels: bug

#11 Add search functionality for documentation
  package-lock.json
  package.json
  src/_includes/layouts/base.njk
  src/_includes/layouts/docs.njk
  src/_includes/partials/header.njk
  src/assets/css/base/base.css
  src/assets/css/components/pagefind.css
  src/assets/css/main.css
  src/assets/js/main.js
  src/assets/js/modules/Alpine.data/DOM.js
  src/assets/js/modules/_loadStylesheet.js
  src/content/_headers.njk
  tailwind.config.js
Labels: enhancement, good first issue

#12 Toggle search input focus and blur on overlay toggle
  src/assets/js/modules/Alpine.data/DOM.js
Labels: enhancement, good first issue

#13 Hide cocktail emoji in header
  src/_includes/partials/header.njk
  src/assets/images/logo-cut.png
Labels: enhancement

#14 Optimization
  cfg/_11ty/shortcodes.js
  src/_includes/layouts/base.njk
  src/_includes/layouts/docs.njk
  src/_includes/partials/header.njk
  src/assets/js/modules/Alpine.data/DOM.js
  src/public/site-dark.webmanifest
  tailwind.config.js
Labels: enhancement, good first issue

#16 Add critical CSS and HTML minification transforms
  .eleventy.js
  cfg/_11ty/transforms.js
  package-lock.json
  package.json
  src/_includes/layouts/base.njk
  src/content/sitemap_xml.njk
  src/content/sitemap_xsl.njk
Labels: enhancement

#17 Optimization
  LICENSE
  LICENSE.md
  README.md
  cfg/_11ty/filters.js
  package-lock.json
  package.json
  src/_data/menu/main.yaml
  src/_includes/layouts/authors.njk
  src/_includes/layouts/base.njk
  src/_includes/partials/footer.njk
  src/assets/js/main.js
  src/assets/js/modules/Alpine.data/DOM.js
  src/assets/js/modules/tracker.js
  src/content/authors.njk
  src/content/authors/atenlotrad.md
  src/content/authors/loraider259.md
  src/content/license.md
  src/content/license.njk
  src/content/robots_txt.njk
Labels: enhancement

#19 Update navigation bar docs
  _content/docs/modules/accordion/index.md
  _content/docs/modules/button/index.md
  _content/docs/modules/card/index.md
  _content/docs/modules/codepen/index.md
  _content/docs/modules/divider/index.md
  _content/docs/modules/github/index.md
  _content/docs/modules/global-footer/index.md
  _content/docs/modules/navigation-bar/dropdown-level-three.png
  _content/docs/modules/navigation-bar/dropdown-level-two.png
  _content/docs/modules/navigation-bar/dropdown-three-settings.png
  _content/docs/modules/navigation-bar/dropdown-two-settings.png
  _content/docs/modules/navigation-bar/index.md
  _content/docs/modules/navigation-bar/nav-bar.png
  _content/docs/modules/pricing-card/index.md
  _content/docs/modules/social-icons/index.md
  _content/docs/modules/statistics/index.md
  _content/docs/modules/testimonials/index.md
  _content/docs/modules/video-embed/index.md
  _content/docs/sections/hero-banner/index.md
  _content/docs/sections/multi-column-content/index.md
  _includes/partials/header.njk
Labels: documentation

#20 Optimization
  _content/_redirects.njk
  _css/base/base.css
  _css/components/buttons.css
  _css/components/pagefind.css
  _includes/partials/header.njk
  _js/main.js
  _layouts/base.njk
  _layouts/docs.njk
  package-lock.json
  package.json
  tailwind.config.js
Labels: enhancement

#21 Set permalink for download page
  _content/download.njk
Labels: bug, good first issue

#22 Optimization
  _includes/partials/header.njk
  _includes/partials/logo.njk
  _static/android-chrome-192x192.png
  _static/android-chrome-512x512.png
  _static/apple-touch-icon.png
  _static/browserconfig.xml
  _static/favicon-16x16.png
  _static/favicon-32x32.png
  _static/favicon.ico
  _static/img/logo-cut.png
  _static/img/logo.jpg
  _static/img/logo.png
  _static/mstile-150x150.png
  _static/safari-pinned-tab.svg
  _static/site.webmanifest
Labels: enhancement
