Repository freshjuice-dev/freshjuice.dev, pull requests merged in 2024-09, with the labels that each got.

#24 Add new blog post on the top 4 search engines of 2024
  _content/blog/2024-08-25-top-4-best-search-engines-of-2024/index.md
  _content/blog/2024-08-25-top-4-best-search-engines-of-2024/planting-trees.jpg
  _content/blog/2024-08-25-top-4-best-search-engines-of-2024/search-engine-home-page.jpg
  _content/blog/2024-08-25-top-4-best-search-engines-of-2024/searching-browsing-concept.jpg
  _static/img/og/blog-top-4-best-search-engines-of-2024.png
Labels: new-blog

#25 Add blog post on best AI writing tools for 2024
  _content/blog/2024-08-31-best-ai-writing-tools-2024/camping-writing-journal.jpg
  _content/blog/2024-08-31-best-ai-writing-tools-2024/concept-of-learning-english-searching-for-word-and-information.jpg
  _content/blog/2024-08-31-best-ai-writing-tools-2024/idea-interpreted.jpg
  _content/blog/2024-08-31-best-ai-writing-tools-2024/index.md
  _static/img/og/blog-best-ai-writing-tools-2024.png
Labels: new-blog

#26 Enhance metadata for social media previews
  _layouts/base.njk
Labels: enhancement

#27 Add external links and update HTML minification
  _11ty/transforms.js
  _content/blog/2024-08-31-best-ai-writing-tools-2024/index.md
  package-lock.json
  package.json
Labels: enhancement

#28 Update blog
  _content/blog/2024-08-25-top-4-best-search-engines-of-2024/index.md
  _content/blog/2024-08-31-best-ai-writing-tools-2024/index.md
  _css/base/base.css
  _includes/partials/header.njk
  _includes/partials/logo.njk
  _static/img/og/authors-atenlotrad.png
Labels: enhancement

#30 update breadcrumbs
  _layouts/docs.njk
  package-lock.json
  package.json
Labels: enhancement

#31 Update blog
  _content/blog/2024-09-06-make-the-perfect-keywords-research/index.md
  _content/blog/2024-09-06-make-the-perfect-keywords-research/keyword-concept-composed-with-multi-colored-stones-over-black-volcanic-sand.jpg
  _content/blog/2024-09-06-make-the-perfect-keywords-research/reflection-magnifying-glass-on-a-black-acrylic-board-with-blue-background.jpg
  _static/img/og/blog-make-the-perfect-keywords-research.png
Labels: new-blog

#32 Init schema markup
  _11ty/filters.js
  _11ty/transforms.js
  _content/404.njk
  _content/authors/atenlotrad.md
  _data/metadata.js
  _includes/partials/schema-markup.njk
  _layouts/base.njk
  _static/img/logo.png
Labels: enhancement

#33 Update schema markup and add organization email
  _data/metadata.js
  _includes/partials/schema-markup.njk
Labels: bug, enhancement

#34 Add blog post on the importance of schema markup for SEO
  _content/blog/2024-09-10-why-schema-markup-is-important/index.md
  _content/blog/2024-09-10-why-schema-markup-is-important/man-hands-pointing-coding-html-and-programming-develop-on-screen-computer.jpg
  _content/blog/2024-09-10-why-schema-markup-is-important/serp-search-engine-results-page.jpg
  _content/blog/2024-09-10-why-schema-markup-is-important/software-developer-working-with-html-script.jpg
Labels: new-blog

#35 Add image for blog post on schema markup
  _static/img/og/blog-why-schema-markup-is-important.png
Labels: new-blog

#36 Update logo image
  _static/img/logo.png
Labels: enhancement

#38 Update blog, feed, and tags
  _11ty/filters.js
  _11ty/transforms.js
  _content/blog/2024-09-15-page-speed-and-seo-2024/business.jpg
  _content/blog/2024-09-15-page-speed-and-seo-2024/index.md
  _content/blog/2024-09-15-page-speed-and-seo-2024/pagespeed-insights.png
  _content/blog/2024-09-15-page-speed-and-seo-2024/speed-motion-on-night-road.jpg
  _content/changelog.md
  _content/feed_json.njk
  _content/feed_xml.njk
  _content/tags-list.njk
  _content/tags.njk
  _layouts/author.njk
  _layouts/base.njk
  _layouts/post.njk
  _static/img/og/blog-page-speed-and-seo-2024.png
  eleventy.config.js
  package-lock.json
  package.json
Labels: enhancement

#40 Add cheerio to filters and change post content to summary
  _11ty/filters.js
  _content/feed_json.njk
  _content/feed_xml.njk
Labels: enhancement

#42 Update blog
  _content/blog.njk
  _content/blog/2024-08-18-seo-optimization-for-search-engines/index.md
  _content/blog/2024-09-19-best-cms-platform-2024/colored-pencils-on-an-open-texture-table-set-of-colored-pencils-on-the-background-of-the-table.jpg
  _content/blog/2024-09-19-best-cms-platform-2024/content-management-system.jpg
  _content/blog/2024-09-19-best-cms-platform-2024/index.md
  _content/blog/2024-09-19-best-cms-platform-2024/typing-up-my-blog-post-of-the-weekend.jpg
  _content/tags.njk
  _layouts/author.njk
  _static/img/og/blog-best-cms-platform-2024.png
Labels: enhancement, new-blog

#43 update documentation autumn 2024
  _content/blog/2024-09-20-our-autumn-big-new-release/cat-drinking.jpg
  _content/blog/2024-09-20-our-autumn-big-new-release/index.md
  _content/changelog.md
  _static/img/og/blog-our-autumn-big-new-release.png
Labels: documentation, new-blog

#44 Update blog posts for clearer links and tag consistency
  _content/blog/2024-08-05-2024-summer-updates/index.md
  _content/blog/2024-09-20-our-autumn-big-new-release/index.md
Labels: enhancement

#45 Update license to MIT in changelog
  _content/changelog.md
Labels: enhancement

#46 Documentation september update2024
  _content/authors/zapalblizh.md
  _content/blog/2024-09-20-2024-autumn-big-release-update/cat-drinking.jpg
  _content/blog/2024-09-20-2024-autumn-big-release-update/index.md
  _content/docs/modules/button/button.png
  _content/docs/modules/button/index.md
  _content/docs/modules/card/card.png
  _content/docs/modules/card/index.md
  _content/docs/modules/flip-cards/flip-cards.png
  _content/docs/modules/flip-cards/index.md
  _content/docs/modules/pricing-card/pricing-cards.png
  _content/docs/templates/contact/contact.png
  _content/docs/templates/pricing/pricing.png
  _data/menu/docs.yaml
Labels: documentation, enhancement

#47 Update blog
  _static/img/og/blog-2024-autumn-big-release-update.png
  _static/img/og/docs-modules-flip-cards.png
Labels: enhancement

#48 Add blog on 6 best HubSpot features for businesses
  _content/blog/2024-09-27-6-best-hubspot-features-for-business/ai-enhanced-education-the-bright-future-of-learning-and-innovation-driven-by-ai.jpg
  _content/blog/2024-09-27-6-best-hubspot-features-for-business/hubspot-logo.png
  _content/blog/2024-09-27-6-best-hubspot-features-for-business/index.md
  _content/blog/2024-09-27-6-best-hubspot-features-for-business/social-media-influencer-holding-like.jpg
Labels: new-blog

#49 add og image
  _static/img/og/blog-6-best-hubspot-features-for-business.png
Labels: new-blog

#50 init list docs
  _content/_redirects.njk
  _content/docs/modules/list/index.md
  _content/docs/modules/list/list.png
  _content/docs/modules/pricing-cards/index.md
  _content/docs/modules/pricing-cards/price-card-with-details.png
  _content/docs/modules/pricing-cards/pricing-card.png
  _content/docs/modules/pricing-cards/pricing-cards.png
  _data/menu/docs.yaml
  _static/img/og/docs-modules-list.png
  _static/img/og/docs-modules-pricing-cards.png
Labels: documentation
